name: snidanok
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_feather_icons: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Thin.ttf
          weight: 100
        - asset: assets/fonts/raleway/Raleway-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/raleway/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/raleway/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/raleway/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/raleway/Raleway-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/raleway/Raleway-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/raleway/Raleway-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/raleway/Raleway-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/raleway/Raleway-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/raleway/Raleway-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/raleway/Raleway-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/raleway/Raleway-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/raleway/Raleway-BlackItalic.ttf
          weight: 900
          style: italic

    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/nunito/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/nunito/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/nunito/Nunito-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/nunito/Nunito-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/nunito/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/nunito/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/nunito/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/nunito/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/nunito/Nunito-BlackItalic.ttf
          weight: 900
          style: italic
